PATH_TO_YOUR_LARAVEL_APP=/path/to/your/laravel/app
VOLUME_MAP=$(PATH_TO_YOUR_LARAVEL_APP):/var/www/html

DB_ROOT_PASS=db_root_pass
DB_NAME=db_name
DB_USER=db_user
DB_USER_PASS=db_user_pass


all: \
	set-permissions \
	build \
	run \
	install-composer \
	install-php \
	custom


build: \
	copy \
	build-mysql-ds \
	build-app-ds \
	build-apache-php \
	build-composer \
	build-php

build-mysql-ds:
	docker build -t mysql_ds mysql_ds/

build-app-ds:
	docker build -t app_ds app_ds/

build-apache-php:
	docker build -t apache_php apache_php/

build-composer:
	docker build -t composer composer/

build-php:
	docker build -t php php/


run: run-mysql-ds run-app-ds run-mysql run-apache-php

run-mysql-ds:
	docker run --name mysql_ds mysql_ds true

run-app-ds:
	docker run --name app_ds -v $(VOLUME_MAP) app_ds true

run-mysql:
	docker run -p 3306:3306 --name mysql --volumes-from mysql_ds \
		-e MYSQL_ROOT_PASSWORD=$(DB_ROOT_PASS) \
		-e MYSQL_DATABASE=$(DB_NAME) \
		-e MYSQL_USER=$(DB_USER) \
		-e MYSQL_PASSWORD=$(DB_USER_PASS) \
		-d mysql:5.7 \
		--max-allowed-packet=33554432 \
		--character-set-server=utf8 \
		--collation-server=utf8_general_ci

run-apache-php:
	docker run -p 80:80 --name apache_php --link mysql:mysql \
		--volumes-from app_ds -d apache_php


copy:
	cp php.ini apache_php/
	cp php.ini php/

set-permissions:
	sudo chmod -R o+w $(PATH_TO_YOUR_LARAVEL_APP)/storage
	sudo chmod -R o+w $(PATH_TO_YOUR_LARAVEL_APP)/bootstrap/cache

custom:
	echo 'custom comands here'

install-composer:
	sudo cp ./composer.sh /usr/local/bin/composer -f
	sudo chmod +x /usr/local/bin/composer

install-php:
	sudo cp ./php.sh /usr/local/bin/php -f
	sudo chmod +x /usr/local/bin/php

